### PR TITLE
updated model to delete dependent caravans and bookings

### PR DESCRIPTION
**Pull request by Jordan-Patel**
I added dependent: :destroy for bookings and caravan when the user is deleted

### CODE REVIEW

**Comment by Akki-on-Rails** [comment]
We also have to set the link to edit or delete a user account in the navbar!

**Review by Akki-on-Rails — APPROVED** [review]

**Comment by Jordan-Patel** [comment]
Ok, I will add a profile page where that can be handled as part of this branch

**Comment by Akki-on-Rails** [comment]
Watch out! There is already an edit page that only needs to be linked.

**Comment by Akki-on-Rails** [comment]
Watch out! There is already an edit page in views/devise/registration that only needs to be linked.

**Comment by Jordan-Patel** [comment]
I added an edit button in the dashboard, that links to the edit.html page. The profile can then be edited or deleted from there.
I also updated the edit page style.

**Pull request merged**
